# Generated by Django 4.1.7 on 2023-03-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_address_teacher_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='classname',
        ),
    ]
